# 1. Titkos konfiguráció (Secret) az adatbázis jelszavaknak
apiVersion: v1
kind: Secret
metadata:
  name: device-db-secret
type: Opaque
stringData: # A K8s automatikusan base64 kódolásba teszi a stringData-t
  MONGO_ROOT_USER: "admin"
  MONGO_ROOT_PASSWORD: "MesteriPassword123!"
  MONGO_URI: "mongodb://admin:MesteriPassword123!@device-db-service:27017/device_db?authSource=admin"

---
# 2. Adatbázis Konténer (Deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-db
  template:
    metadata:
      labels:
        app: device-db
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: device-db-secret
              key: MONGO_ROOT_USER
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: device-db-secret
              key: MONGO_ROOT_PASSWORD

---
# 3. Adatbázis Belső Hálózat (Service)
apiVersion: v1
kind: Service
metadata:
  name: device-db-service
spec:
  selector:
    app: device-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
