apiVersion: v1
kind: ConfigMap
metadata:
  name: device-app-config
data:
  PORT: "3000"
---
# === DEVICE ADATBÁZIS (POSTGRESQL) ===
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-db
  template:
    metadata:
      labels:
        app: device-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: device_db
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: device-db-service
spec:
  selector:
    app: device-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
# === DEVICE SERVICE (NODE.JS) ===
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-service
  template:
    metadata:
      labels:
        app: device-service
    spec:
      containers:
      - name: device-service
        image: selod/iot-device-service:latest
        imagePullPolicy: Always   # <--- GARANTÁLJA A FRISSÜLÉST
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: device-app-config
              key: PORT
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@device-db-service:5432/device_db"
---
apiVersion: v1
kind: Service
metadata:
  name: device-app-service
spec:
  selector:
    app: device-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: device-ingress
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /api/devices
        pathType: Prefix
        backend:
          service:
            name: device-app-service
            port:
              number: 80