apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-db
  template:
    metadata:
      labels:
        app: device-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: device_db
---
apiVersion: v1
kind: Service
metadata:
  name: device-db-service
spec:
  selector:
    app: device-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP