apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: frontend.167.233.130.203.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-app-service # Győződj meg róla, hogy ez a Service neved a frontend-app.yaml-ben!
            port:
              number: 80               # A Service-ben megadott port