# 1. Olvasható konfiguráció
apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-app-config
data:
  PORT: "3001"

---
# 2. A Te Telemetry Alkalmazásod (Deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-service
  template:
    metadata:
      labels:
        app: telemetry-service
    spec:
      containers:
      - name: telemetry-service
        image: selod/iot-telemetry-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: telemetry-app-config
              key: PORT
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: telemetry-db-secret
              key: DATABASE_URL
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10

---
# 3. Alkalmazás Belső Hálózat (Service)
apiVersion: v1
kind: Service
metadata:
  name: telemetry-app-service
spec:
  selector:
    app: telemetry-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP

---
# 4. Külvilág felé nyitás (Ingress a /api/telemetry útvonalra)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telemetry-ingress
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /api/telemetry
        pathType: Prefix
        backend:
          service:
            name: telemetry-app-service
            port:
              number: 80