server {
    listen 80;
    server_name localhost;

    # Gzip tömörítés bekapcsolása a gyorsabb betöltésért
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Ez a sor KÖTELEZŐ egy React/SPA alkalmazásnál! 
        # Ha a user frissíti az oldalt, az Nginx mindig az index.html-t adja vissza.
        try_files $uri $uri/ /index.html;
    }
}